name: Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  blackbird:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory to backend
        run: cd backend

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24.0"

      - name: Verify Go installation
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Run Blackbird
        uses: ryanmello/blackbird@v1.0.1
